export const ALL = 'all'

export const HTML = 'html'
export const JAVASCRIPT = 'javascript'
export const TYPESCRIPT = 'typescript'
export const REACT = 'react'
export const VUE = 'vue'
export const REDUX = 'redux'
export const SVG = 'svg'
export const PUG = 'pug'
export const SCSS = 'scss'
export const CSS3 = 'css3'
export const RXJS = 'rxjs'

export const CODEPEN = 'codepen'
export const GITHUB = 'github'
export const SKILLSHARE = 'skillshare'
